spring:
  application:
    name: gemini-upms
  profiles:
    active: dev
    include: cloud
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://docker-server:3306/upms?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  data:
    redis:
      host: docker-server
      port: 6379
      database: 7
      timeout: 10000
  cache:
    type: redis
    redis:
      cache-null-values: true
      key-prefix: "gemini-upms:cache:"
      time-to-live: 1000
  cloud:
    inetutils:
      preferred-networks:
        - 192.168.31.

gemini:
  open-api:
    enabled: true
    info:
      version: 1.0.0
      title: Gemini UPMS Boot
      description: Gemini UPMS Boot
      contact:
        name: george
        email: george@gls.com
        url: https://www.gls.com
      license:
        name: Apache License 2.0
        url: https://www.apache.org/licenses/LICENSE-2.0.html
        identifier: Apache-2.0
  redis:
    cache:
      - cache-name: "demo-service:vo"
        time-to-live: 3600000
  xxl-job:
    admin-addresses: http://docker-server:48080/xxl-job-admin
    ip: 192.168.31.13
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl