spring:
  application:
    name: gemini-upms
  profiles:
    active: dev
    include: cloud
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://docker-server:3306/upms?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root

gemini:
  open-api:
    enabled: true
    info:
      version: 1.0.0
      title: Gemini UPMS Boot
      description: Gemini UPMS Boot
      contact:
        name: george
        email: george@gls.com
      license:
        name: Apache License 2.0
        url: http://www.apache.org/licenses/LICENSE-2.0.html